config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'chatroom#index'

  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  resources :users, except: %i[new create]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'message', to: 'messages#create'

  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  belongs_to :user
  validates :body, presence: true
  scope :custom_display, -> { order(:created_at).last(20) }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :messages
  validates :username, presence: true,
                       uniqueness: { case_sensitive: false },
                       length: { minimum: 3, maximum: 15 }
  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    length: { maximum: 105 },
                    format: { with: URI::MailTo::EMAIL_REGEXP }

  has_secure_password
  validates :password, confirmation: true
  validates :password_confirmation, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  http_basic_authenticate_with name: "dlaSopla", password: "apkaDoKontaktu"
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    unless logged_in?
      flash[:error] = 'You must be logged in.'
      redirect_to login_path
    end
  end
end

app/controllers/chatroom_controller.rb
# frozen_string_literal: true

class ChatroomController < ApplicationController
  before_action :require_user

  def index
    @message = Message.new
    @users = User.all
    # render :index, locals: { messages: Message.order('created_at ASC').includes(:user) }
    render :index, locals: { messages: Message.includes(:user).custom_display }
  end
end

app/controllers/messages_controller.rb
# frozen_string_literal: true

class MessagesController < ApplicationController
  before_action :require_user

  def create
    message = current_user.messages.build(message_params)
    if message.save
      ActionCable.server.broadcast 'chatroom_channel',
                                   mod_message: message_render(message)

    end
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end

  def message_render(message)
    render(partial: 'message', locals: { message: message })
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  before_action :logged_in_redirect, only: %i[new create]

  def new; end

  def create
    user = User.find_by(username: params[:session][:username])
    if user&.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = 'Welcome! You have been succesfully logged in.'
      redirect_to root_path
    else
      flash.now[:error] = 'Wrong username or password.'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'Bye! You have been succesfully logged out.'
    redirect_to login_path
  end

  private

  def logged_in_redirect
    if logged_in?
      flash[:error] = 'You are already logged in.'
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: %i[edit update destroy]

  def index
    render :index, locals: { users: User.all.order('username ASC') }
  end

  def new
    render :new, locals: { user: User.new }
  end

  def create
    user = User.new(user_params)
    if user.save
      flash[:success] = 'Welcome! You have been succesfully registered.'
      session[:user_id] = user.id
      redirect_to root_path
    else
      render :new, locals: { user: user }
    end
  end

  def edit
    render :edit, locals: { user: user }
  end

  def update
    if user.update(user_params)
      flash[:success] = 'Your account has been successfully updated.'
      redirect_to root_path
    else
      render :edit, locals: { user: user }
    end
  end

  def destroy
    user.destroy
    flash[:warning] = 'Your account has been successfully deleted. Good bye - see you!'
    redirect_to root_path
  end

  private

  def user
    user ||= User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def correct_user
    flash[:error] = 'You are not authorized.' unless user == current_user
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/chatroom/index.html.erb
<h3 class="ui center aligned icon header">
  <i class="circular orange rocketchat icon", id="icon"></i>
  Chat with your friends!
</h3>

<div class="ui two column grid">
  <div class="twelve wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content" id="messages">
        <div class="ui feed" id="message-container">
          <%= render messages %>
        </div>
      </div>
      <div class="extra content">
        <%= form_for(@message, html: {class: "ui reply form", role: "form"}, url: message_path, remote: true) do |f| %>
          <div class="field">
            <div class="ui fluid icon input">
              <%= f.text_field :body, placeholder:"Enter a message..." %>
              <%= f.button '<i class="bordered inverted orange edit icon"></i>'.html_safe %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="four wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content">
        <div class="ui inverted vertical menu">
          <a class="item">
            Users:
          </a>
          <% @users.each do |user| %>
            <a class="item">
              <%= user.username %>
            </a>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div class="ui container">
    <ul>
      <div class="ui error message transition">
        <% obj.errors.full_messages.each do |error| %>
          <i class="close icon"></i>
          <div class="header">
            <li><%= error %></li>
          </div>
        <% end %>
      </div>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="ui inverted vertical footer segment form-page">
  <div class="ui container center aligned row">
    <small class="chat_with_me">ChatWithMe</small> &copy; <%= link_to "GitHub", "https://github.com/iAcay/chat_with_me", target: "_blank", class: "text-white" %>
  </div>
</div>

app/views/layouts/_messages.html.erb
<div class="ui container">
  <% flash.each do |message_type, message_content| %>
    <div class="ui <%= message_type %> message transition">
        <i class="close icon"></i>
        <div class="header">
          <%= message_content %>
        </div>
      </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<div class="ui large inverted menu">
  <%= link_to 'ChatWithMe', (logged_in? ? root_path : login_path), class: 'item', id: 'logo' %>
  <%= link_to 'Chatroom', root_path, class: 'item' %>
  <div class="right menu">
    <% if logged_in? %>
      <div class="ui dropdown item">
      Account <i class="dropdown icon"></i>
        <div class="menu">
          <%= link_to 'Logout', logout_path, class: 'item', method: :delete %>
        </div>
      </div>
    <% else %>
      <div class="item">
          <%= link_to 'Log in', login_path, class: "ui inverted orange button" %>
          <%= link_to 'Sign up', signup_path, class: "ui inverted orange button" %> 
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatWithMe</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="ui container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
  <div class="content">
    <div class="summary">
      <em><%= message.user.username %></em>: <%= message.body %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1 class="ui center aligned icon header">Welcome to <strong class="chat_with_me">ChatWithMe</strong></h1>
<h3 class="ui center aligned icon header">
  <i class="circular orange pencil alternate icon", id="icon"></i>
</h3>
<h3 class="ui horizontal divider header">Sign up and chat with us!</h3>
<%= render 'layouts/errors', obj: user %>
<div class="ui placeholder segment">
  <div class="ui very relaxed stackable grid">
    <div class="column">
      <%= form_for(:user, html: {class: "ui form", role: "form"}, url: signup_path) do |f| %>
        <div class="field">
          <%= f.label :username, "Username" %>
          <div class="ui left icon input">
            <%= f.text_field :username, placeholder: "Username" %>
            <i class="user icon"></i>
          </div>
        </div>
        <div class="field">
          <%= f.label :email, "Email" %>
          <div class="ui left icon input">
            <%= f.email_field :email, placeholder: "Email" %>
            <i class="envelope icon"></i>
          </div>
        </div>
        <div class="field">
          <%= f.label :password, "Password" %>
          <div class="ui left icon input">
            <%= f.password_field :password, placeholder: "Password" %>
            <i class="lock icon"></i>
          </div>
        </div>
        <div class="field">
          <%= f.label :password_confirmation, "Password confirmation" %>
          <div class="ui left icon input">
            <%= f.password_field :password_confirmation, placeholder: "Password confirmation" %>
            <i class="lock icon"></i>
          </div>
        </div>
        <%= f.button "Sign up!", class: "ui orange submit button" %>
      <% end %>
    </div>
  </div>
</div>